swagger: '2.0'
info:
  version: '1.0'
  title: CADC Target Name Resolver
  description: '<p>
    The CADC Target Name Resolver is a simple web application that services HTTP GET requests to
    resolve astronomical object names to RA and DEC coordinates. Name Resolver
    concurrently queries one or more services to resolve the object name,
    returning the first positive result. The services queried are:
  </p>
  
    <table>
      <tr>
        <th nowrap="true">Service</th>
        <th>Description</th>
      </tr>
      <tr">
        <td nowrap="true"><a href="http://nedwww.ipac.caltech.edu/index.html">NED</a></td>
        <td>The NASA/IPAC ExtraGalactic Database at the
          California Institute of Technology (CalTech).
        </td>
      </tr>
      <tr">
        <td nowrap="true"><a href="http://simbad.u-strasbg.fr/simbad/">Simbad</a></td>
        <td>The SIMBAD Astronomical Database at the Centre de Donn&#233;es
          astronomiques de Strasbourg (CDS).
        </td>
      </tr>
      <tr>
        <td nowrap="true"><a href="http://vizier.u-strasbg.fr/viz-bin/VizieR">VizieR</a></td>
        <td>The VizieR service at CDS.</td>
      </tr>
    </table>'
schemes:
  - https
basePath: /cadc-target-resolver
paths:
  /find:
    get:
      description: |
       Resolve an astronomical object name to RA and DEC coordinates.
      tags:
        - Target resolver
      summary: Return RA and DEC for an object name
      responses:
        '404':
          description: |
            If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
        - name: target
          in: query
          description: |
            Name of the object to resolve. Examples: target=M31
          required: true
          type: string
        - name: service
          in: query
          description: |
            Services to query. Examples: service=NED
          required: false
          default: ALL
          enum:
            - NED
            - SIMBAD
            - VIZIER
            - ALL
          type: string
          collectionFormat: multi
        - name: format
          in: query
          description: |
            Response FORMAT. Examples: format=JSON
          required: false
          type: string
          default: ASCII
          enum:
            - ASCII
            - JSON
        - name: cached
          in: query
          description: |
            Whether to return previous cached results. Examples: cached=YES
          required: false
          type: boolean
          default: YES
          enum:
            - YES
            - NO
        - name: detail
          in: query
          description: |
            Details to return. Examples: detail=MAX
                * MIN - default fields:
                    * target: the target name to resolve.
                    * service: the service that resolved the object.
                    * coordsys: the coordinates system, always ICRS.
                    * ra: the right ascension of the object in degrees.
                    * dec: the declination of the object in degrees.
                    * time: time in milliseconds to resolve the object.
                * MAX - default with following additional fields:
                    * oname: the service preferred object name.
                    * otype: the object type code.
                    * mtype: the object morphology type.
          required: false
          type: string
          default: MIN
          enum:
            - MIN
            - MAX
  /availability:
    get:
      tags:
        - Support Interfaces
      summary: VOSI Availability
      description: 'Indicates whether the service is operable and shows the reliability of the service for extended and scheduled requests. If the query parameter ''detail=min'' is used, a light weight heart beat test will be performed. The heart beat test returns status 200 if the service is available.'
      parameters:
        - name: detail
          in: query
          description: 'Specifies heart beat to be used to check for availability of this service, the value ''min'' must be used, otherwise the full availability test will be performed'
          required: false
          type: string
      responses:
        '200':
          description: A VOSI availability document in XML.
  /capabilities:
    get:
      summary: VOSI Capabilities
      tags:
        - Support Interfaces
      description: |
        Provides the service metadata in the form of a list of Capability descriptions.  Each of these descriptions is an XML element that:
        <ul>
        <li>states that the service provides a particular, IVOA-standard function;</li>
        <li>lists the interfaces for invoking that function;</li>
        <li>records any details of the implementation of the function that are not defined as default or constant in the standard for that function.</li>
        </ul>
      responses:
        '200':
          description: A VOSI Capabilities document in XML.
        '500':
          description: Internal server error
        '503':
          description: Service too busy
